#Global config
#ListeningDevice = "lo"

#DHCP config
DisableDHCP=false
DestinationHost = "localhost"
DestinationPort = 67
Filter = "udp and port 68 and ((udp[284:1] = 0x3) or (udp[284:1] = 0x5))"

#DNS config
DisableDNS=false
DNSDestinationHost = "localhost"
DNSDestinationPort = 53
DNSFilter = "udp and port 53"
